### ISSUE TITLE
IllegalStateException in NamespaceChangeStreamListener - Android Todo sample app; not sync'ing

### ISSUE THREAD

**Issue by SogoGolf** [mongodb/stitch-examples#85] opened 2019-01-11 00:19 UTC
hi, nice work with Stitch and Stitch sync beta. 

when running the Todo sync sample app for Android, i noticed that if i made a change ON THE SERVER via the Stitch web UI, to a document in the collection (ie todo.items)  --> that change would NOT sync back to the running Android app. 

looking in the logs I saw this:
```
2019-01-11 11:13:51.022 15480-16912/com.mongodb.stitch.sdk.examples.todo E/items: NamespaceChangeStreamListener::stream ns=todo.items exception on fetching next event: java.lang.IllegalStateException: expected updatedFields to be present
    java.lang.IllegalStateException: expected updatedFields to be present
```

Is this a bug with the Stitch sync API ? 

Also, this error listener/handler in the sample Android app did not trigger. I would have thought that it should have ?

```
 private class MyErrorListener implements ErrorListener {
        @Override
        public void onError(BsonValue documentId, Exception error) {
            Log.e("Stitch", error.getLocalizedMessage());

            Set<BsonValue> docsThatNeedToBeFixed = _remoteCollection.sync().getPausedDocumentIds();
            for (BsonValue doc_id : docsThatNeedToBeFixed) {
                // Add your logic to inform the user.
                // When errors have been resolved, call
                _remoteCollection.sync().resumeSyncForDocument(doc_id);
            }
        }
    }
```

**Comment by adamchel** [comment] 2019-01-22 14:09
Hi @SogoGolf, this bug should be fixed now, let us know if you have any further issues!

**Comment by SogoGolf** [comment] 2019-01-22 21:58
thanks @adamchel ! do i need to update the gradle version  ?

**Comment by adamchel** [comment] 2019-01-22 22:46
Hmm, I have not seen that error before. We currently run a set of integration tests before releasing that is separate from the ToDo example app, so it's possible this issue was not caught. I will reopen this issue and investigate it tomorrow.

**Comment by SogoGolf** [comment] 2019-01-22 22:52
thanks @adamchel . might be worth checking that the integration tests check the sync api from both directions (offline scenario i guess)  ie. data change/sync from client -> server, data change/sync from server -> client

**Comment by SogoGolf** [comment] 2019-01-23 06:02
hey @adamchel i noticed in the documentation today that any "external" changes made to Atlas collections that are being sync'd, must have their ```__stitch_sync_version```'s ```v``` property manually incremented by whatever external app is making a change to that document. 

so i made a change to one of those sync'd Todo items AND i incremented that ```v``` property. The "MuUpdateListener" callback in the Android app then immediately triggered and carried with it the data change made on the server side "manually".

so that server -> client flow is working as intended which is great. 

lastly, that error log above seems to be related to auth. i didn't enable facebook and google auth so am wondering if the error is related to that ?

**Comment by adamchel** [comment] 2019-01-23 15:08
Hi @SogoGolf, I'm glad to hear you resolved the issue. We'll look into more prominently documenting that caveat.

As for the error log, it seems to indicate a `TRANSPORT_ERROR`, which is usually due to an intermittent network issue. Are you consistently seeing that error or did you only see it once? If you're consistently seeing it, please let me know the steps to reproduce it so I can investigate it further.

**Comment by MongoCaleb** [comment] 2019-01-24 18:03
@SogoGolf I'm closing this, as it was an issue with not setting the version. That being said, I have a ticket to look at ways we can call out that "gotcha" more prominently in the docs.

**Closed by MongoCaleb** 2019-01-24 18:03 UTC

**Comment by adamchel** [comment] 2019-01-24 18:18
@SogoGolf if you continue to see that other error, please open an issue at https://github.com/mongodb/stitch-android-sdk
